"""The changelog generator (`marimo-book sync-releases`)."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

import marimo_book.release_notes as rn
from marimo_book.cli import app
from marimo_book.config import Book, ReleaseNotes
from marimo_book.release_notes import _demote_h1, render_changelog_markdown

RELEASES = [
    {
        "tag_name": "v0.8.10",
        "name": "v0.8.10",
        "published_at": "2026-06-14T11:35:38Z",
        "html_url": "https://github.com/o/r/releases/tag/v0.8.10",
        "prerelease": False,
        "draft": False,
        "body": "### Fixed\n\n- Cache-bust the SPA entry document.",
    },
    {
        "tag_name": "v0.8.9",
        "name": "Shiny title",
        "published_at": "2026-06-14T04:48:14Z",
        "html_url": "https://github.com/o/r/releases/tag/v0.8.9",
        "prerelease": True,
        "draft": False,
        "body": "# Big heading in body\n\nNotes.",
    },
]


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


# --- markdown rendering ------------------------------------------------------


def test_render_has_title_and_generated_marker():
    md = render_changelog_markdown(RELEASES, repo="o/r", title="My Changelog")
    assert md.startswith("# My Changelog")
    assert "Generated by `marimo-book sync-releases`" in md


def test_render_orders_newest_first_with_dates_and_links():
    md = render_changelog_markdown(RELEASES, repo="o/r")
    assert md.index("## v0.8.10") < md.index("## Shiny title")
    assert "_Released 2026-06-14_" in md
    assert "https://github.com/o/r/releases/tag/v0.8.10" in md


def test_render_embeds_body_and_marks_prerelease():
    md = render_changelog_markdown(RELEASES, repo="o/r")
    assert "Cache-bust the SPA entry document." in md
    assert "**pre-release**" in md  # v0.8.9 is a prerelease


def test_render_demotes_h1_in_body():
    md = render_changelog_markdown(RELEASES, repo="o/r")
    lines = md.split("\n")
    # The body's "# Big heading" must not render as a page-level H1 line.
    assert "# Big heading in body" not in lines
    assert "### Big heading in body" in lines


def test_render_empty_releases():
    md = render_changelog_markdown([], repo="o/r", title="CL")
    assert "No releases published yet" in md
    assert "github.com/o/r/releases" in md


def test_demote_h1_leaves_fenced_code_alone():
    src = "# Title\n\n```\n# not a heading\n```\n## sub"
    out = _demote_h1(src)
    assert out.startswith("### Title")
    assert "# not a heading" in out  # inside fence, untouched
    assert "## sub" in out  # H2 untouched


# --- config ------------------------------------------------------------------


def test_release_notes_config_defaults():
    rn_cfg = ReleaseNotes()
    assert rn_cfg.repo is None
    assert rn_cfg.output == Path("changelog.md")
    assert rn_cfg.include_prereleases is True


def test_book_release_notes_optional_and_parsed():
    book = Book(title="T", toc=[], release_notes={"repo": "o/r", "title": "CL"})
    assert book.release_notes is not None
    assert book.release_notes.repo == "o/r"
    # Absent by default.
    assert Book(title="T", toc=[]).release_notes is None


# --- CLI ---------------------------------------------------------------------


def _book(tmp_path: Path, **rn_kwargs) -> Path:
    import yaml

    cfg = {"title": "T", "toc": [{"file": "changelog.md"}]}
    if rn_kwargs:
        cfg["release_notes"] = rn_kwargs
    p = tmp_path / "book.yml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    return p


def test_sync_releases_writes_file(runner, tmp_path, monkeypatch):
    monkeypatch.setattr(rn, "fetch_releases", lambda *a, **k: RELEASES)
    book = _book(tmp_path, repo="o/r", title="CL")
    result = runner.invoke(app, ["sync-releases", "-b", str(book)])
    assert result.exit_code == 0, result.output
    out = (tmp_path / "changelog.md").read_text(encoding="utf-8")
    assert "## v0.8.10" in out
    assert out.startswith("# CL")


def test_sync_releases_check_flags_stale(runner, tmp_path, monkeypatch):
    monkeypatch.setattr(rn, "fetch_releases", lambda *a, **k: RELEASES)
    book = _book(tmp_path, repo="o/r")
    # No file yet → stale → --check exits 1 and writes nothing.
    result = runner.invoke(app, ["sync-releases", "-b", str(book), "--check"])
    assert result.exit_code == 1
    assert not (tmp_path / "changelog.md").exists()


def test_sync_releases_idempotent(runner, tmp_path, monkeypatch):
    monkeypatch.setattr(rn, "fetch_releases", lambda *a, **k: RELEASES)
    book = _book(tmp_path, repo="o/r")
    runner.invoke(app, ["sync-releases", "-b", str(book)])
    # Second run is a no-op, and --check now passes.
    result = runner.invoke(app, ["sync-releases", "-b", str(book), "--check"])
    assert result.exit_code == 0, result.output


def test_sync_releases_requires_block(runner, tmp_path):
    book = _book(tmp_path)  # no release_notes block
    result = runner.invoke(app, ["sync-releases", "-b", str(book)])
    assert result.exit_code == 2
    assert "release_notes" in result.output


# --- fetch_releases (pagination + filtering, urlopen monkeypatched) ----------


class _FakeResp:
    def __init__(self, payload: str):
        self._payload = payload.encode("utf-8")

    def read(self):
        return self._payload

    def __enter__(self):
        return self

    def __exit__(self, *a):
        return False


def _fake_urlopen_factory(pages):
    """Return a urlopen stub that serves successive JSON pages by ?page=N."""
    import json as _json

    def _open(req, timeout=None):
        # req is a urllib Request; pull the page number from the URL.
        url = req.full_url
        page = int(url.split("&page=")[1]) if "&page=" in url else 1
        body = pages[page - 1] if page - 1 < len(pages) else []
        return _FakeResp(_json.dumps(body))

    return _open


def test_fetch_releases_paginates_and_filters(monkeypatch):
    page1 = [{"tag_name": f"v{i}", "draft": False, "prerelease": False} for i in range(100)]
    page1[0]["draft"] = True  # dropped
    page1[1]["prerelease"] = True  # kept by default, dropped when excluded
    page2 = [{"tag_name": "v100", "draft": False, "prerelease": False}]
    monkeypatch.setattr(
        rn.urllib.request, "urlopen", _fake_urlopen_factory([page1, page2])
    )

    all_rel = rn.fetch_releases("o/r")
    # 100 on page 1 minus 1 draft = 99, plus 1 on page 2 = 100.
    assert len(all_rel) == 100
    assert all(not r["draft"] for r in all_rel)

    no_pre = rn.fetch_releases("o/r", include_prereleases=False)
    assert len(no_pre) == 99  # the one prerelease also dropped


def test_fetch_releases_limit_stops_early(monkeypatch):
    page1 = [{"tag_name": f"v{i}", "draft": False, "prerelease": False} for i in range(100)]
    monkeypatch.setattr(
        rn.urllib.request, "urlopen", _fake_urlopen_factory([page1, []])
    )
    assert len(rn.fetch_releases("o/r", limit=5)) == 5


def test_fetch_releases_rejects_non_list(monkeypatch):
    monkeypatch.setattr(
        rn.urllib.request, "urlopen", lambda req, timeout=None: _FakeResp('{"message":"boom"}')
    )
    with pytest.raises(ValueError):
        rn.fetch_releases("o/r")


def test_sync_releases_falls_back_to_book_repo(runner, tmp_path, monkeypatch):
    import yaml

    captured = {}

    def fake_fetch(repo, **k):
        captured["repo"] = repo
        return RELEASES

    monkeypatch.setattr(rn, "fetch_releases", fake_fetch)
    # release_notes present but no repo → use book.repo
    cfg = {
        "title": "T",
        "repo": "https://github.com/o/r",
        "toc": [{"file": "changelog.md"}],
        "release_notes": {"title": "CL"},
    }
    p = tmp_path / "book.yml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    result = runner.invoke(app, ["sync-releases", "-b", str(p)])
    assert result.exit_code == 0, result.output
    assert captured["repo"] == "https://github.com/o/r"
