"""Generate a changelog page from a repo's GitHub Releases.

This backs the ``marimo-book sync-releases`` command. Like ``sync-deps`` and
``render``, it's a *generate-then-build* step: it fetches releases over the
network and writes a committed Markdown page, so the regular ``build`` stays
hermetic (no network) and reproducible. Wire it to run in CI on a
``repository_dispatch`` from the app repo when a new release publishes.

The network fetch uses only the standard library (``urllib``) so marimo-book
gains no new dependency. A ``GITHUB_TOKEN`` in the environment is used when
present — required for private repos, and it lifts the API rate limit.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request

from .release_download import normalize_repo

_API = "https://api.github.com"
_GENERATED_MARKER = "<!-- Generated by `marimo-book sync-releases`. Do not edit by hand. -->"


def fetch_releases(
    repo: str,
    *,
    token: str | None = None,
    limit: int | None = None,
    include_prereleases: bool = True,
    timeout: float = 30.0,
) -> list[dict]:
    """Fetch releases for ``repo`` (``owner/name`` or a GitHub URL), newest first.

    Drafts are always excluded. Prereleases are kept unless
    ``include_prereleases`` is false. Paginates the Releases API; ``limit``
    caps the number returned. Raises ``urllib.error.HTTPError`` /
    ``URLError`` on network or API failure so the caller can report it.
    """
    owner_repo = normalize_repo(repo)
    token = token if token is not None else os.environ.get("GITHUB_TOKEN")
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "marimo-book",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    out: list[dict] = []
    page = 1
    while True:
        url = f"{_API}/repos/{owner_repo}/releases?per_page=100&page={page}"
        req = urllib.request.Request(url, headers=headers)  # noqa: S310 (https only)
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            batch = json.loads(resp.read().decode("utf-8"))
        if not isinstance(batch, list):
            raise ValueError(
                f"unexpected GitHub API response for {owner_repo} "
                f"(expected a list of releases, got {type(batch).__name__})"
            )
        if not batch:
            break
        for rel in batch:
            if rel.get("draft"):
                continue
            if rel.get("prerelease") and not include_prereleases:
                continue
            out.append(rel)
            if limit is not None and len(out) >= limit:
                return out
        if len(batch) < 100:
            break
        page += 1
    return out


def render_changelog_markdown(
    releases: list[dict],
    *,
    repo: str,
    title: str = "Changelog",
) -> str:
    """Render releases into a Markdown changelog page (pure; no network).

    Each release becomes a ``## <name>`` section with its publish date, a
    link to the release on GitHub, and its body (GitHub-flavoured Markdown,
    embedded verbatim). Newest first.
    """
    owner_repo = normalize_repo(repo)
    lines: list[str] = [f"# {title}", "", _GENERATED_MARKER, ""]

    if not releases:
        lines.append(
            f"_No releases published yet. See "
            f"[{owner_repo} on GitHub](https://github.com/{owner_repo}/releases)._"
        )
        return "\n".join(lines) + "\n"

    for rel in releases:
        tag = rel.get("tag_name") or ""
        name = rel.get("name") or tag or "(untitled release)"
        date = (rel.get("published_at") or "")[:10]
        html_url = rel.get("html_url") or f"https://github.com/{owner_repo}/releases"
        prerelease = rel.get("prerelease", False)

        # Collapse any whitespace/newlines so a multi-line release name can't
        # break the heading into a heading + stray body line.
        heading = " ".join(str(name).split()) or "(untitled release)"
        lines.append(f"## {heading}")
        lines.append("")
        meta = []
        if date:
            meta.append(f"_Released {date}_")
        if tag and tag != name:
            meta.append(f"[`{tag}`]({html_url})")
        else:
            meta.append(f"[Release notes]({html_url})")
        if prerelease:
            meta.append("**pre-release**")
        lines.append(" · ".join(meta))
        lines.append("")

        body = (rel.get("body") or "").strip()
        if body:
            # Normalise CRLF from the API and demote any H1 in the body so it
            # doesn't compete with the per-release H2 heading.
            body = body.replace("\r\n", "\n")
            lines.extend(_demote_headings(body).split("\n"))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


_ATX_HEADING = re.compile(r"(#{1,6})\s")


def _demote_headings(markdown: str, by: int = 2) -> str:
    """Demote every ATX heading in a release body by ``by`` levels.

    Each release renders under a ``## <version>`` heading, so the body's own
    headings must sit *below* H2 or they collide with the page structure — e.g.
    a release note's ``## Installation`` would otherwise render at the same
    level as the version. Shift all headings down (H1→H3, H2→H4, …), capped at
    H6. Fenced code blocks are left untouched.
    """
    out: list[str] = []
    in_fence = False
    for line in markdown.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            out.append(line)
            continue
        m = None if in_fence else _ATX_HEADING.match(stripped)
        if m:
            level = min(len(m.group(1)) + by, 6)
            out.append("#" * level + stripped[m.end(1) :])
        else:
            out.append(line)
    return "\n".join(out)
