"""Generate a changelog page from a repo's GitHub Releases.

This backs the ``marimo-book sync-releases`` command. Like ``sync-deps`` and
``render``, it's a *generate-then-build* step: it fetches releases over the
network and writes a committed Markdown page, so the regular ``build`` stays
hermetic (no network) and reproducible. Wire it to run in CI on a
``repository_dispatch`` from the app repo when a new release publishes.

The network fetch uses only the standard library (``urllib``) so marimo-book
gains no new dependency. A ``GITHUB_TOKEN`` in the environment is used when
present — required for private repos, and it lifts the API rate limit.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request

from .release_download import normalize_repo

_API = "https://api.github.com"
_GENERATED_MARKER = "<!-- Generated by `marimo-book sync-releases`. Do not edit by hand. -->"


def fetch_releases(
    repo: str,
    *,
    token: str | None = None,
    limit: int | None = None,
    include_prereleases: bool = True,
    timeout: float = 30.0,
) -> list[dict]:
    """Fetch releases for ``repo`` (``owner/name`` or a GitHub URL), newest first.

    Drafts are always excluded. Prereleases are kept unless
    ``include_prereleases`` is false. Paginates the Releases API; ``limit``
    caps the number returned. Raises ``urllib.error.HTTPError`` /
    ``URLError`` on network or API failure so the caller can report it.
    """
    owner_repo = normalize_repo(repo)
    token = token if token is not None else os.environ.get("GITHUB_TOKEN")
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "marimo-book",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    out: list[dict] = []
    page = 1
    while True:
        url = f"{_API}/repos/{owner_repo}/releases?per_page=100&page={page}"
        req = urllib.request.Request(url, headers=headers)  # noqa: S310 (https only)
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            batch = json.loads(resp.read().decode("utf-8"))
        if not batch:
            break
        for rel in batch:
            if rel.get("draft"):
                continue
            if rel.get("prerelease") and not include_prereleases:
                continue
            out.append(rel)
            if limit is not None and len(out) >= limit:
                return out
        if len(batch) < 100:
            break
        page += 1
    return out


def render_changelog_markdown(
    releases: list[dict],
    *,
    repo: str,
    title: str = "Changelog",
) -> str:
    """Render releases into a Markdown changelog page (pure; no network).

    Each release becomes a ``## <name>`` section with its publish date, a
    link to the release on GitHub, and its body (GitHub-flavoured Markdown,
    embedded verbatim). Newest first.
    """
    owner_repo = normalize_repo(repo)
    lines: list[str] = [f"# {title}", "", _GENERATED_MARKER, ""]

    if not releases:
        lines.append(
            f"_No releases published yet. See "
            f"[{owner_repo} on GitHub](https://github.com/{owner_repo}/releases)._"
        )
        return "\n".join(lines) + "\n"

    for rel in releases:
        tag = rel.get("tag_name") or ""
        name = rel.get("name") or tag or "(untitled release)"
        date = (rel.get("published_at") or "")[:10]
        html_url = rel.get("html_url") or f"https://github.com/{owner_repo}/releases"
        prerelease = rel.get("prerelease", False)

        heading = name
        lines.append(f"## {heading}")
        lines.append("")
        meta = []
        if date:
            meta.append(f"_Released {date}_")
        if tag and tag != name:
            meta.append(f"[`{tag}`]({html_url})")
        else:
            meta.append(f"[Release notes]({html_url})")
        if prerelease:
            meta.append("**pre-release**")
        lines.append(" · ".join(meta))
        lines.append("")

        body = (rel.get("body") or "").strip()
        if body:
            # Normalise CRLF from the API and demote any H1 in the body so it
            # doesn't compete with the per-release H2 heading.
            body = body.replace("\r\n", "\n")
            lines.extend(_demote_h1(body).split("\n"))
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _demote_h1(markdown: str) -> str:
    """Demote top-level ``# `` headings in a release body to ``### ``.

    Release bodies occasionally open with their own ``# Title``; left as-is
    that would render as a page-level H1 mid-page. Shift only leading-``#``
    lines (not ``##`` etc.) down two levels. Fenced code blocks are left
    untouched.
    """
    out: list[str] = []
    in_fence = False
    for line in markdown.split("\n"):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence and stripped.startswith("# "):
            out.append("### " + stripped[2:])
        else:
            out.append(line)
    return "\n".join(out)
